version: '3.8'

services:
  db:
    build:
      context: db
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "psql -U postgres -h db -p 5432 -c 'SELECT 1'"
      timeout: 60s
      interval: 10s

  server:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  ui:
    image: node:lts
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    working_dir: /ui
    healthcheck:
      test: "ls dist"
      timeout: 60s
      interval: 10s
    entrypoint: bash -c "npm ci && npm run dev"